### ISSUE TITLE
Why don't you provide a wheel for pypi?

### ISSUE THREAD

**Issue by Jerry-Master** [Pseudomanifold/Aleph#57]
The process could be handled automatically for windows and linux with github actions. You just need to create a workflow similar to this one:

```
name: Publish Python 🐍 package to PyPI

on:
  push:
    tags:
      - 'v*'  # Only runs when you push a tag like v0.1.0

permissions:
  contents: read

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
```

Where instead of `python -m build` which is the command for a pure python package that step would contains all the commands necessary to compile the library and bindings. Maybe some extra step is required to bundle all the dependencies but that should be it.
